-- Msic Queries
    CONNECT sys as sysdba;
    Oradoc_db1
    SELECT * FROM ALL_USERS;
    SELECT table_name FROM user_tables;  
    select table_name FROM all_tables; 

-- creating an user
    CONNECT sys as sysdba;
    Oradoc_db1
    CREATE USER shrestharajat IDENTIFIED BY 1357;
    ALTER USER shrestharajat ACCOUNT UNLOCK;
    GRANT resource To shrestharajat;
    GRANT create session TO shrestharajat;
    GRANT connect, resource, dba to shrestharajat;
    CONNECT shrestharajat
    1357




-- DDL Script

    -- Generated by Oracle SQL Developer Data Modeler 4.1.5.907
    --   at:        2020-02-16 21:11:20 NPT
    --   site:      Oracle Database 11g
    --   type:      Oracle Database 11g




    CREATE TABLE Activity
    (
        Activity_ID   VARCHAR2 (50) NOT NULL ,
        Activity_Name VARCHAR2 (250) NOT NULL ,
        Travel_Mode   VARCHAR2 (250) NOT NULL
    ) ;
    ALTER TABLE Activity ADD CONSTRAINT Activity_PK PRIMARY KEY ( Activity_ID ) ;


    CREATE TABLE Customer
    (
        Customer_ID VARCHAR2 (50) NOT NULL ,
        First_Name  VARCHAR2 (250) NOT NULL ,
        Last_Name   VARCHAR2 (250) NOT NULL ,
        Address     VARCHAR2 (250) NOT NULL ,
        Phone_No    VARCHAR2 (50) NOT NULL
    ) ;
    ALTER TABLE Customer ADD CONSTRAINT Customer_PK PRIMARY KEY ( Customer_ID ) ;


    CREATE TABLE Customer_Package
    (
        Customer_ID VARCHAR2 (50) NOT NULL ,
        Package_ID  VARCHAR2 (50) NOT NULL
    ) ;
    ALTER TABLE Customer_Package ADD CONSTRAINT Customer_Package_PK PRIMARY KEY ( Package_ID, Customer_ID ) ;


    CREATE TABLE Day_Activities
    (
        Package_ID  VARCHAR2 (50) NOT NULL ,
        DAY         VARCHAR2 (50) NOT NULL ,
        Activity_ID VARCHAR2 (50) NOT NULL ,
        Status      VARCHAR2 (250) NOT NULL
    ) ;
    ALTER TABLE Day_Activities ADD CONSTRAINT Day_Activities_PK PRIMARY KEY ( Activity_ID, Package_ID, DAY ) ;


    CREATE TABLE Destination
    (
        Package_ID  VARCHAR2 (50) NOT NULL ,
        Destination VARCHAR2 (250) NOT NULL
    ) ;
    ALTER TABLE Destination ADD CONSTRAINT Destination_Package_PK PRIMARY KEY ( Destination, Package_ID ) ;


    CREATE TABLE Itinerary
    (
        Package_ID       VARCHAR2 (50) NOT NULL ,
        DAY              VARCHAR2 (50) NOT NULL ,
        Difficulty_Level VARCHAR2 (250) NOT NULL ,
        Travel_Details   VARCHAR2 (250) NOT NULL
    ) ;
    ALTER TABLE Itinerary ADD CONSTRAINT Itenary_PK PRIMARY KEY ( DAY, Package_ID ) ;


    CREATE TABLE Package_Guide
    (
        Package_ID VARCHAR2 (50) NOT NULL ,
        Staff_ID   VARCHAR2 (50) NOT NULL
    ) ;
    ALTER TABLE Package_Guide ADD CONSTRAINT Package_Guide_PK PRIMARY KEY ( Package_ID, Staff_ID ) ;


    CREATE TABLE Packages
    (
        Package_ID   VARCHAR2 (50) NOT NULL ,
        Package_Name VARCHAR2 (250) NOT NULL ,
        Total_Days   INTEGER NOT NULL ,
        Start_Date   DATE NOT NULL ,
        End_Date     DATE NOT NULL ,
        Difficulty   VARCHAR2 (250) NOT NULL
    ) ;
    ALTER TABLE Packages ADD CONSTRAINT Packages_PK PRIMARY KEY ( Package_ID ) ;


    CREATE TABLE Role
    (
        Role_ID     VARCHAR2 (50) NOT NULL ,
        Description VARCHAR2 (250) NOT NULL
    ) ;
    ALTER TABLE Role ADD CONSTRAINT Role_PK PRIMARY KEY ( Role_ID ) ;


    CREATE TABLE Staff
    (
        Staff_ID   VARCHAR2 (50) NOT NULL ,
        First_Name VARCHAR2 (250) NOT NULL ,
        Last_Name  VARCHAR2 (250) NOT NULL ,
        Address    VARCHAR2 (250) NOT NULL ,
        Phone_No   VARCHAR2 (250) NOT NULL ,
        Role_ID    VARCHAR2 (250) NOT NULL
    ) ;
    ALTER TABLE Staff ADD CONSTRAINT Staff_PK PRIMARY KEY ( Staff_ID ) ;


    ALTER TABLE Customer_Package ADD CONSTRAINT Customer_Package_Customer_FK FOREIGN KEY ( Customer_ID ) REFERENCES Customer ( Customer_ID ) ;

    ALTER TABLE Customer_Package ADD CONSTRAINT Customer_Package_Packages_FK FOREIGN KEY ( Package_ID ) REFERENCES Packages ( Package_ID ) ;

    ALTER TABLE Day_Activities ADD CONSTRAINT Day_Activities_Activity_FK FOREIGN KEY ( Activity_ID ) REFERENCES Activity ( Activity_ID ) ;

    ALTER TABLE Day_Activities ADD CONSTRAINT Day_Activities_Itinerary_FK FOREIGN KEY ( DAY, Package_ID ) REFERENCES Itinerary ( DAY, Package_ID ) ;

    ALTER TABLE Destination ADD CONSTRAINT Destination_Packages_FK FOREIGN KEY ( Package_ID ) REFERENCES Packages ( Package_ID ) ;

    ALTER TABLE Itinerary ADD CONSTRAINT Itinerary_Packages_FK FOREIGN KEY ( Package_ID ) REFERENCES Packages ( Package_ID ) ;

    ALTER TABLE Package_Guide ADD CONSTRAINT Package_Guide_Packages_FK FOREIGN KEY ( Package_ID ) REFERENCES Packages ( Package_ID ) ;

    ALTER TABLE Package_Guide ADD CONSTRAINT Package_Guide_Staff_FK FOREIGN KEY ( Staff_ID ) REFERENCES Staff ( Staff_ID ) ;

    ALTER TABLE Staff ADD CONSTRAINT Staff_Role_FK FOREIGN KEY ( Role_ID ) REFERENCES Role ( Role_ID ) ;


    -- Oracle SQL Developer Data Modeler Summary Report: 
    -- 
    -- CREATE TABLE                            10
    -- CREATE INDEX                             0
    -- ALTER TABLE                             19
    -- CREATE VIEW                              0
    -- ALTER VIEW                               0
    -- CREATE PACKAGE                           0
    -- CREATE PACKAGE BODY                      0
    -- CREATE PROCEDURE                         0
    -- CREATE FUNCTION                          0
    -- CREATE TRIGGER                           0
    -- ALTER TRIGGER                            0
    -- CREATE COLLECTION TYPE                   0
    -- CREATE STRUCTURED TYPE                   0
    -- CREATE STRUCTURED TYPE BODY              0
    -- CREATE CLUSTER                           0
    -- CREATE CONTEXT                           0
    -- CREATE DATABASE                          0
    -- CREATE DIMENSION                         0
    -- CREATE DIRECTORY                         0
    -- CREATE DISK GROUP                        0
    -- CREATE ROLE                              0
    -- CREATE ROLLBACK SEGMENT                  0
    -- CREATE SEQUENCE                          0
    -- CREATE MATERIALIZED VIEW                 0
    -- CREATE SYNONYM                           0
    -- CREATE TABLESPACE                        0
    -- CREATE USER                              0
    -- 
    -- DROP TABLESPACE                          0
    -- DROP DATABASE                            0
    -- 
    -- REDACTION POLICY                         0
    -- 
    -- ORDS DROP SCHEMA                         0
    -- ORDS ENABLE SCHEMA                       0
    -- ORDS ENABLE OBJECT                       0
    -- 
    -- ERRORS                                   0
    -- WARNINGS                                 0


-- describe the tables
    describe day_activities;
    describe activity;
    describe itinerary;
    describe destination;
    describe packages;
    describe customer_package;
    describe package_guide;
    describe customer;
    describe staff;
    describe role;

-- Populating the database
    INSERT INTO packages (PACKAGE_ID, PACKAGE_NAME, TOTAL_DAYS, START_DATE, END_DATE, DIFFICULTY) 
        WITH names AS ( 
            SELECT 'GAND8', 'Ghandruk', 4, '01-JAN-2020',   '04-JAN-2020', 'Moderate' FROM dual UNION ALL 
            SELECT 'ABC21', 'Annapurna BC', 6, '12-FEB-2020',   '17-FEB-2020', 'Hard' FROM dual UNION ALL 
            SELECT 'PUNH1', 'Poon-Hill', 5, '01-JAN-2020',   '05-JAN-2020', 'Hard' FROM dual UNION ALL 
            SELECT 'EBC77', 'Everest BC', 8, '01-JAN-2020',   '08-JAN-2020', 'Hard' FROM dual UNION ALL 
            SELECT 'LUKL1', 'Lukla', 3, '01-MAR-2020',   '03-MAR-2020', 'Moderate' FROM dual 
        ) 
        SELECT * FROM names;


    INSERT INTO destination (PACKAGE_ID, DESTINATION) 
        WITH names AS ( 
            SELECT 'GAND8', 'Pokhara' FROM dual UNION ALL
            SELECT 'GAND8', 'Ghandruk' FROM dual UNION ALL
            SELECT 'ABC21', 'Pokhara' FROM dual UNION ALL
            SELECT 'ABC21', 'Ghandruk' FROM dual UNION ALL
            SELECT 'ABC21', 'ABC' FROM dual UNION ALL
            SELECT 'PUNH1', 'Pokhara' FROM dual UNION ALL
            SELECT 'PUNH1', 'Ghorepani' FROM dual UNION ALL
            SELECT 'PUNH1', 'PoonHill' FROM dual UNION ALL
            SELECT 'PUNH1', 'Ghandruk' FROM dual UNION ALL
            SELECT 'LUKL1', 'Lukla' FROM dual UNION ALL
            SELECT 'EBC77', 'Lukla' FROM dual UNION ALL
            SELECT 'EBC77', 'Namche-Bazzar' FROM dual UNION ALL
            SELECT 'EBC77', 'Dingboche' FROM dual UNION ALL
            SELECT 'EBC77', 'EBC' FROM dual
            ) 
        SELECT * FROM names;


    INSERT INTO itinerary (PACKAGE_ID, DAY, TRAVEL_DETAILS, DIFFICULTY_LEVEL) 
        WITH names AS ( 
            SELECT 'GAND8', 'day-1', 'Kathmandu-Pokhara', 'Easy' FROM dual UNION ALL
            SELECT 'GAND8', 'day-2', 'Pokhara-Ghandruk', 'Hard' FROM dual UNION ALL
            SELECT 'GAND8', 'day-3', 'Ghandruk-Pokhara', 'Hard' FROM dual UNION ALL
            SELECT 'GAND8', 'day-4', 'Pokhara-Kathmandu', 'Easy' FROM dual UNION ALL
            --
            SELECT 'ABC21', 'day-1', 'Kathmandu-Pokhara', 'Easy' FROM dual UNION ALL
            SELECT 'ABC21', 'day-2', 'Pokhara-Ghandruk', 'Hard' FROM dual UNION ALL
            SELECT 'ABC21', 'day-3', 'Ghandruk-ABC', 'Hard' FROM dual UNION ALL
            SELECT 'ABC21', 'day-4', 'ABC-Ghandruk', 'Hard' FROM dual UNION ALL
            SELECT 'ABC21', 'day-5', 'Ghandruk-Pokhara', 'Hard' FROM dual UNION ALL
            SELECT 'ABC21', 'day-6', 'Pokhara-Kathmandu', 'Easy' FROM dual UNION ALL
            --
            SELECT 'PUNH1', 'day-1', 'Kathmandu-Pokhara', 'Easy' FROM dual UNION ALL
            SELECT 'PUNH1', 'day-2', 'Pokhara-Ghorepani', 'Hard' FROM dual UNION ALL
            SELECT 'PUNH1', 'day-3', 'Gorepani-Ghandruk', 'Hard' FROM dual UNION ALL
            SELECT 'PUNH1', 'day-4', 'Ghandruk-Pokhara', 'Hard' FROM dual UNION ALL
            SELECT 'PUNH1', 'day-5', 'Pokhara-Kathmandu', 'Easy' FROM dual UNION ALL
            --
            SELECT 'LUKL1', 'day-1', 'Kathmandu-Lukla', 'Easy' FROM dual UNION ALL
            SELECT 'LUKL1', 'day-2', 'Lukla', 'Easy' FROM dual UNION ALL
            SELECT 'LUKL1', 'day-3', 'Lukla-Kathmandu', 'Easy' FROM dual UNION ALL
            --
            SELECT 'EBC77', 'day-1', 'Kathmandu-Lukla', 'Easy' FROM dual UNION ALL
            SELECT 'EBC77', 'day-2', 'Lukla-Namche Bazzar', 'Hard' FROM dual UNION ALL
            SELECT 'EBC77', 'day-3', 'Namche Bazzar-Dingboche', 'Hard' FROM dual UNION ALL
            SELECT 'EBC77', 'day-4', 'Dingboche-EBC', 'Hard' FROM dual UNION ALL
            SELECT 'EBC77', 'day-5', 'EBC-Dingboche', 'Hard' FROM dual UNION ALL
            SELECT 'EBC77', 'day-6', 'Dingboche-Namche Bazzar', 'Hard' FROM dual UNION ALL
            SELECT 'EBC77', 'day-7', 'Namche Bazzar-Lukla', 'Easy' FROM dual UNION ALL
            SELECT 'EBC77', 'day-8', 'Lukla-Kathmandu', 'Easy' FROM dual
        )
        SELECT * FROM names; 


    INSERT INTO activity (ACTIVITY_ID, ACTIVITY_NAME, TRAVEL_MODE) 
        WITH names AS ( 
            SELECT 'A1', 'Driving from KTM to Pokhara', 'bus' FROM dual UNION ALL
            SELECT 'A2', 'Overnight stay in Hotel', 'stay' FROM dual UNION ALL
            SELECT 'A3', 'Trek to Ghandruk', 'walk' FROM dual UNION ALL
            SELECT 'A4', 'Explore the Ghandruk Village', 'walk' FROM dual UNION ALL
            SELECT 'A5', 'View the sunrise and Himalayas', 'walk' FROM dual UNION ALL
            SELECT 'A6', 'Trek Down to Pokhara', 'walk' FROM dual UNION ALL
            SELECT 'A7', 'Drive back to Kathmandu', 'walk' FROM dual UNION ALL
            --
            SELECT 'A8', 'Trek to ABC from Ghandruk', 'walk' FROM dual UNION ALL
            SELECT 'A9', 'Explore ABC', 'walk' FROM dual UNION ALL
            SELECT 'A10', 'Trek back to Ghandruk from ABC', 'walk' FROM dual UNION ALL
            --
            SELECT 'A11', 'Bus to halfway for ghorepani', 'walk' FROM dual UNION ALL
            SELECT 'A12', 'Trek to Ghorepani', 'walk' FROM dual UNION ALL
            SELECT 'A13', 'Hike to Poonhill', walk FROM dual UNION ALL
            SELECT 'A14', 'Viewing Sunrise', 'walk' FROM dual UNION ALL
            --
            SELECT 'A15', 'Flight to Lukla', 'plane' FROM dual UNION ALL
            SELECT 'A16', 'Explore Lukla', 'walk' FROM dual UNION ALL
            SELECT 'A17', 'Overnight stay in Lukla', 'stay' FROM dual UNION ALL
            SELECT 'A18', 'Flight From Lukla to kathmandu', 'plane' FROM dual UNION ALL
            SELECT 'A19', 'Hike from Lukla to Namche bazzar', 'walk' FROM dual UNION ALL
            --
            SELECT 'A20', 'Trek from Namche bazzar to Dingboche', 'walk' FROM dual UNION ALL
            SELECT 'A21', 'Trek from Dingboche to EBC', 'walk' FROM dual UNION ALL
            SELECT 'A22', 'Explore EBC', 'walk' FROM dual UNION ALL
            SELECT 'A23', 'Trek from EBC to Dingboche', 'walk' FROM dual UNION ALL
            SELECT 'A24', 'Trek from Dingboche to Namche bazzar', 'walk' FROM dual UNION ALL
            SELECT 'A25', 'Trek from Namche bazzar to Lukla', 'walk' FROM dual
        ) 
        SELECT * FROM names; 


    INSERT INTO day_activities (PACKAGE_ID, DAY, ACTIVITY_ID, STATUS) 
        WITH names AS ( 
            SELECT 'GAND8', 'day-1', 'A1', 'Incomplete' FROM dual UNION ALL
            SELECT 'GAND8', 'day-1', 'A2', 'Incomplete' FROM dual UNION ALL
            SELECT 'GAND8', 'day-2', 'A3', 'Incomplete' FROM dual UNION ALL
            SELECT 'GAND8', 'day-2', 'A4', 'Incomplete' FROM dual UNION ALL
            SELECT 'GAND8', 'day-3', 'A5', 'Incomplete' FROM dual UNION ALL
            SELECT 'GAND8', 'day-4', 'A6', 'Incomplete' FROM dual UNION ALL
            --
            SELECT 'ABC21', 'day-1', 'A1', 'Incomplete' FROM dual UNION ALL
            SELECT 'ABC21', 'day-1', 'A2', 'Incomplete' FROM dual UNION ALL
            SELECT 'ABC21', 'day-2', 'A3', 'Incomplete' FROM dual UNION ALL
            SELECT 'ABC21', 'day-2', 'A4', 'Incomplete' FROM dual UNION ALL
            SELECT 'ABC21', 'day-3', 'A8', 'Incomplete' FROM dual UNION ALL
            SELECT 'ABC21', 'day-3', 'A9', 'Incomplete' FROM dual UNION ALL
            SELECT 'ABC21', 'day-4', 'A10', 'Incomplete' FROM dual UNION ALL
            SELECT 'ABC21', 'day-5', 'A5', 'Incomplete' FROM dual UNION ALL
            SELECT 'ABC21', 'day-6', 'A6', 'Incomplete' FROM dual UNION ALL
            --
            SELECT 'PUNH1', 'day-1', 'A1', 'Incomplete' FROM dual UNION ALL
            SELECT 'PUNH1', 'day-1', 'A2', 'Incomplete' FROM dual UNION ALL
            SELECT 'PUNH1', 'day-2', 'A11', 'Incomplete' FROM dual UNION ALL
            SELECT 'PUNH1', 'day-2', 'A12', 'Incomplete' FROM dual UNION ALL
            SELECT 'PUNH1', 'day-3', 'A13', 'Incomplete' FROM dual UNION ALL
            SELECT 'PUNH1', 'day-3', 'A14', 'Incomplete' FROM dual UNION ALL
            SELECT 'PUNH1', 'day-3', 'A3', 'Incomplete' FROM dual UNION ALL
            SELECT 'PUNH1', 'day-4', 'A5', 'Incomplete' FROM dual UNION ALL
            SELECT 'PUNH1', 'day-5', 'A6', 'Incomplete' FROM dual UNION ALL
            --
            SELECT 'LUKL1', 'day-1' , 'A15', 'Incomplete' FROM dual UNION ALL
            SELECT 'LUKL1', 'day-1' , 'A16', 'Incomplete' FROM dual UNION ALL
            SELECT 'LUKL1', 'day-1' , 'A17', 'Incomplete' FROM dual UNION ALL
            SELECT 'LUKL1', 'day-2' , 'A16', 'Incomplete' FROM dual UNION ALL
            SELECT 'LUKL1', 'day-2' , 'A17', 'Incomplete' FROM dual UNION ALL
            SELECT 'LUKL1', 'day-3' , 'A18', 'Incomplete' FROM dual UNION ALL
            --
            SELECT 'EBC77', 'day-1' , 'A15', 'Incomplete' FROM dual UNION ALL
            SELECT 'EBC77', 'day-1' , 'A16', 'Incomplete' FROM dual UNION ALL
            SELECT 'EBC77', 'day-1' , 'A17', 'Incomplete' FROM dual UNION ALL
            SELECT 'EBC77', 'day-2' , 'A19', 'Incomplete' FROM dual UNION ALL
            SELECT 'EBC77', 'day-3' , 'A20', 'Incomplete' FROM dual UNION ALL
            SELECT 'EBC77', 'day-4' , 'A21', 'Incomplete' FROM dual UNION ALL
            SELECT 'EBC77', 'day-4' , 'A22', 'Incomplete' FROM dual UNION ALL
            SELECT 'EBC77', 'day-5' , 'A23', 'Incomplete' FROM dual UNION ALL
            SELECT 'EBC77', 'day-6' , 'A24', 'Incomplete' FROM dual UNION ALL
            SELECT 'EBC77', 'day-7' , 'A25', 'Incomplete' FROM dual UNION ALL
            SELECT 'EBC77', 'day-8' , 'A18', 'Incomplete' FROM dual
        ) 
        SELECT * FROM names;


    INSERT INTO role (ROLE_ID, DESCRIPTION) 
        WITH names AS (
            SELECT 'TA', 'Tour Agent, stays in reception to help customer' FROM dual UNION ALL
            SELECT 'G', 'Guide, goes to tours' FROM dual UNION ALL
            SELECT 'MA', 'Manager, the main manager of the office' FROM dual UNION ALL
            SELECT 'DV', 'Driver, driver for the company' FROM dual UNION ALL
            SELECT 'IN', 'Intern, agent intern in the company' FROM dual
        ) 
        SELECT * FROM names;


    INSERT INTO staff (STAFF_ID, FIRST_NAME, LAST_NAME, ADDRESS, PHONE_NO, ROLE_ID) 
        WITH names AS (
            SELECT 'S001', 'Rajat', 'Shrestha', 'Samakhushi, TownPlanning', '9182934234', 'G' FROM dual UNION ALL
            SELECT 'S002', 'Ashley', 'Green', 'Baluwatar', '9182343123', 'TA' FROM dual UNION ALL
            SELECT 'S003', 'Shia', 'Miton', 'patan', '9182323423', 'TA' FROM dual UNION ALL
            SELECT 'S004', 'Ramendra', 'Sharma', 'Gongabu', '9184322123', 'G' FROM dual UNION ALL
            SELECT 'S005', 'Silas', 'BK', 'Butwal', '9182931112', 'G' FROM dual UNION ALL
            SELECT 'S006', 'Rabin', 'Tamang', 'Sankhamul', '91323934234', 'G' FROM dual UNION ALL
            SELECT 'S007', 'Prabin', 'Maskey', 'Baluwatar', '9182343123', 'G' FROM dual UNION ALL
            SELECT 'S008', 'Pranish', 'Chettri', 'baneshwor', '9132323423', 'IN' FROM dual UNION ALL
            SELECT 'S009', 'Ramu', 'Sharma', 'Gongabu', '9184322123', 'G' FROM dual UNION ALL
            SELECT 'S010', 'Ganesh', 'KC', 'Birendranagar', '9182931112', 'MA' FROM dual
        ) 
        SELECT * FROM names;


    INSERT INTO customer (CUSTOMER_ID, FIRST_NAME, LAST_NAME, ADDRESS, PHONE_NO) 
        WITH names AS (
            SELECT 'C001', 'Ramesh', 'Nakarmi', 'Samakhushi, TownPlanning', '9182934234' FROM dual UNION ALL
            SELECT 'C002', 'John', 'LeBron', 'Baluwatar', '9182343423'  FROM dual UNION ALL
            SELECT 'C003', 'Saran', 'Manandar', 'patan', '9182323433'  FROM dual UNION ALL
            SELECT 'C004', 'Susma', 'Shakya', 'Gongabu', '9184422123' FROM dual UNION ALL
            SELECT 'C005', 'Siliya', 'Malla', 'Butwal', '9182931111'  FROM dual UNION ALL
            SELECT 'C006', 'Shreyash', 'Subedi', 'Sankhamul', '91223934234' FROM dual UNION ALL
            SELECT 'C007', 'Bhuwan', 'Khanal', 'Baluwatar', '9382343123' FROM dual UNION ALL
            SELECT 'C008', 'Prashant', 'Budha', 'baneshwor', '9332323423' FROM dual UNION ALL
            SELECT 'C009', 'Gopal', 'KC', 'Gongabu', '9184323223' FROM dual UNION ALL
            SELECT 'C010', 'Naren', 'Bajracharya', 'Birendranagar', '9123931112'  FROM dual
        ) 
        SELECT * FROM names;

    INSERT INTO customer_package (CUSTOMER_ID, PACKAGE_ID) 
        WITH names AS (
            SELECT 'C001', 'GAND8' FROM dual UNION ALL
            SELECT 'C002', 'EBC77' FROM dual UNION ALL
            SELECT 'C003', 'EBC77' FROM dual UNION ALL
            SELECT 'C004', 'EBC77' FROM dual UNION ALL
            SELECT 'C005', 'PUNH1' FROM dual UNION ALL
            SELECT 'C006', 'ABC21' FROM dual UNION ALL
            SELECT 'C007', 'PUNH1' FROM dual UNION ALL
            SELECT 'C008', 'ABC21' FROM dual UNION ALL
            SELECT 'C009', 'LUKL1' FROM dual UNION ALL
            SELECT 'C010', 'GAND8' FROM dual
        ) 
        SELECT * FROM names;

    INSERT INTO package_guide (PACKAGE_ID, STAFF_ID) 
        WITH names AS (
            SELECT 'GAND8', 'S001' FROM dual UNION ALL
            SELECT 'ABC21', 'S004' FROM dual UNION ALL
            SELECT 'ABC21', 'S005' FROM dual UNION ALL
            SELECT 'PUNH1', 'S006' FROM dual UNION ALL
            SELECT 'EBC77', 'S007' FROM dual UNION ALL
            SELECT 'EBC77', 'S009' FROM dual
        ) 
        SELECT * FROM names;


-- Drop tables
    drop table day_activities;
    drop table activity;
    drop table itinerary;
    drop table destination;
    drop table customer_package;
    drop table package_guide;
    drop table packages;
    drop table customer;
    drop table staff;
    drop table role;

-- deleting the shrestharajat user
    CONNECT system as sysdba;
    1357
    DROP USER shrestharajat CASCADE;
